services:
  - type: web
    name: threat-platform-api
    env: python
    buildCommand: bash build.sh
    startCommand: gunicorn threat_platform.wsgi:application
    envVars:
      - key: DEBUG
        value: "0"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: PYTHON_VERSION
        value: "3.13.7"
      - key: DATABASE_URL
        fromDatabase:
          name: threat-platform-db
          property: connectionString

databases:
  - name: threat-platform-db
    plan: free
